# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='attempts_number',
            field=models.IntegerField(default=0),
        ),
    ]
