# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_test_attempts_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='attempts_number',
            new_name='passes_number',
        ),
    ]
