# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20170321_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='result_text',
            field=models.CharField(max_length=300),
        ),
    ]
