# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_test_attempts_number'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuser',
            name='passed_tests',
            field=models.ManyToManyField(to='testing.Test'),
        ),
    ]
